### ISSUE TITLE
Mod置顶后依旧遇到错误，无法启动

### ISSUE THREAD

**Issue by zzzqh** [NekoCaffeine/SlayTheSpire-FixWordSpacing#1]
[Thread-5] WARN io.sentry.dsn.Dsn - *** Couldn't find a suitable DSN, Sentry operations will do nothing! See documentation: https://docs.sentry.io/clients/java/ ***
[Thread-5] WARN io.sentry.DefaultSentryClientFactory - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames   - 691ms
 - StSLib
   - com.evacipated.cardcrawl.mod.stslib.StSLib
   - 0ms
 - FixWordSpacing(修复单词间距)
   - neko.caffeine.sts.fix.core.Initializer
15:57:54.576 INFO core.Initializer> initialize: sun.instrument.InstrumentationImpl@7aa17a6c
15:57:54.578 INFO core.Initializer> Context class loader: com.evacipated.cardcrawl.modthespire.MTSClassLoader@333634d9
15:57:54.590 INFO core.Initializer> Retransform: com/megacrit/cardcrawl/screens/SingleCardViewPopup(com.evacipated.cardcrawl.modthespire.MTSClassLoader@333634d9)
15:57:54.664 INFO core.Initializer> Retransform: com/megacrit/cardcrawl/helpers/FontHelper(com.evacipated.cardcrawl.modthespire.MTSClassLoader@333634d9)
15:57:54.709 INFO core.Initializer> Retransform: com/megacrit/cardcrawl/events/GenericEventDialog(com.evacipated.cardcrawl.modthespire.MTSClassLoader@333634d9)

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:49)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:449)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:273)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at neko.caffeine.sts.fix.core.Initializer.lambda$initialize$2(Initializer.java:174)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at neko.caffeine.sts.fix.core.Initializer.initialize(Initializer.java:174)
	... 8 more

**Comment by NekoCaffeine** [comment]
我还以为这个问题置顶能解决

**Comment by NekoCaffeine** [comment]
我换个实现方式好了
